name: spider

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Create local changes
      run: |
        npm install
        npm install bangumi-data@latest
        rm .github/workflows/test.yml
    - name: Commit files
      id: commit
      run: |
        git config --local user.email "soekibun+bot@gmail.com"
        git config --local user.name "ekibot"
        time=$(date "+%Y%m%d%H%M%S")
        git add . -v
        git commit -m "Update at ${time}"
        echo ::set-output name=time::$time
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.commit.outputs.time }}
        release_name: Release ${{ steps.commit.outputs.time }}
        body: ${{ steps.commit.outputs.time }}